Tekton Workload Identity
equinor/radix-tekton pull request #102
Opened 2023-12-06 14:00 UTC by Richard87

2023-12-13 12:42 UTC, nilsgstrabo requested changes
Added some suggestions

2023-12-13 12:42 UTC, nilsgstrabo commented on pkg/pipeline/prepare_pipelines.go
> +func validateAzureSkipContainers(task *pipelinev1.Task) {
```suggestion
func sanitizeAzureSkipContainersAnnotation(task *pipelinev1.Task) {
```
Is this a more descriptive name?

2023-12-13 12:42 UTC, nilsgstrabo commented on pkg/pipeline/prepare_pipelines.go
> +	for _, containerName := range skip {
Simplify; always prepend skip items with "step-". Return error if skip item does not exist in task.steps

2023-12-13 12:42 UTC, nilsgstrabo commented on pkg/pipeline/prepare_pipelines.go
> +	tektonInitContainers := []string{"place-scripts", "prepare"}
These should always be included in updatedSkipNames. Init updatedSkipNames with these values

2023-12-13 12:42 UTC, nilsgstrabo commented on pkg/pipeline/radix-application_config.go
> +		cm.ObjectMeta.OwnerReferences = []metav1.OwnerReference{*ctx.ownerReference}
owenrReference is already set in line 60. Can ownerReference be nil? If so, line 60 should be remove

2023-12-13 12:42 UTC, nilsgstrabo commented on pkg/utils/test/setup.go
> +func (params *TestParams) ApplyRd(radixClient radixclient.Interface) (*v1.RadixDeployment, error) {
This method and the TestParams struct is never used. Remove it.

2023-12-14 09:12 UTC, satr requested changes
Suggested changes

2023-12-14 12:09 UTC, Richard87 commented on pkg/pipeline/prepare_pipelines.go
> +	SkipContainers := []string{"place-scripts", "prepare"}
I don't think so, these steps doesn't exist yet as they are first created in the Pod (they are init containers)

2023-12-14 14:31 UTC, satr approved these changes

2023-12-14 14:46 UTC, nilsgstrabo approved these changes

2023-12-14 14:48 UTC, merged