Set refs
equinor/radix-tekton pull request #103
Opened 2023-12-18 14:24 UTC by satr

2023-12-18 15:26 UTC, Richard87 requested changes
Should/could errors be static?

2023-12-18 15:26 UTC, Richard87 commented on pkg/models/env/env.go
> +		errs = append(errs, fmt.Errorf("missing DNS aliases, reserved for Radix platform Radix application"))
Can we make these errors static?

2023-12-18 15:57 UTC, satr commented on pkg/models/env/env.go
> +		errs = append(errs, fmt.Errorf("missing DNS aliases, reserved for Radix platform Radix application"))
Fixed

2023-12-19 07:22 UTC, Richard87 approved these changes
lgtm

2023-12-19 07:24 UTC, merged